name: ci

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npx vitest run

  style:
    name: style
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npx @biomejs/biome check ./src ./test
      - run: npx tsc --noEmit
